# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9c0a4668069e213cd595d2e396627114e4d046147484c73e1621883dfc846bccdd78a01fbfb47d1c63f14e1e2b1b64f4ac2f58ddff62658105c6ffbf3c1deb

test:
  secret_key_base: ea4ca417d4d897501d971891ba6f1e7f124f64de00bb2e9617fcaf6047caa04f2d00f8b4bf01dbba6a0a7688b104b99d38bbf76a028eac85ce5be2170692ccad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
